# generated by chatgpt
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

# Load CSV without header
script_dir = os.path.dirname(os.path.abspath(__file__))
csv_path = os.path.join(script_dir, "test_gradient.csv")
df = pd.read_csv(csv_path, header=None)

# Assign column names manually
columns = ["file"] + [str(i) for i in range(0,64)] + ["last_iteration", "last_value"]
df.columns = columns

# Iteration columns (1 to 64)
iterations = [str(i) for i in range(0,64)]
x = range(0,64)

# Replace -1 with np.nan so calculations work
iter_df = df[iterations].replace(-1, np.nan).astype(float)

# Plot
plt.figure(figsize=(14,7))

# Plot each file as a thin gray line
for _, row in iter_df.iterrows():
    plt.plot(x, row.values, color="gray", alpha=0.4, linewidth=0.7)

# Compute mean across rows
mean_values = iter_df.mean()

# Plot mean curve
plt.plot(x, mean_values, color="blue", linewidth=2, label="Mean")

plt.xlabel("Iterations")
plt.ylabel("Gradient")
plt.legend()
plt.grid(alpha=0.5)
plt.tight_layout()
plt.savefig("graph_gradient.png", dpi=200)
plt.show()
