# generated by chatgpt
import pandas as pd
import matplotlib.pyplot as plt
import os

# Load all CSVs
script_dir = os.path.dirname(os.path.abspath(__file__))
csv_files = ["noFog_gradient.csv", "mediumFog_gradient.csv", "denseFog_gradient.csv"]
labels = ["No Fog", "Medium Fog", "Dense Fog"]  # legend labels

dfs = [pd.read_csv(os.path.join(script_dir, f)) for f in csv_files]

# Iteration columns
iterations = ['0','1','2','4','8','16','32','64']
x_positions = range(len(iterations))

# Colors for each CSV
colors = ["lightblue", "lightgreen", "lightcoral"]

plt.figure(figsize=(14,6))

# Offset for grouping
width = 0.25  # spacing between boxes in a group

for i, (df, color, label) in enumerate(zip(dfs, colors, labels)):
    # Prepare data (replace -1 with NaN, drop NaN)
    data = [df[col].replace(-1, pd.NA).dropna() for col in iterations]
    
    # Shift positions slightly for grouping
    positions = [x + (i - 1) * width for x in x_positions]  
    
    # Draw boxplots
    bp = plt.boxplot(
        data, 
        positions=positions, 
        widths=width*0.8, 
        patch_artist=True, 
        whis=[0,100],  # include all values
        boxprops=dict(facecolor=color, alpha=0.6),
        medianprops=dict(color="black"),
        whiskerprops=dict(color="black"),
        capprops=dict(color="black"),
        flierprops=dict(marker='o', markersize=3, alpha=0.3)  # if you want outliers visible
    )

# X-axis labels in the middle of groups
plt.xticks(x_positions, iterations)

plt.xlabel("Iterations")
plt.ylabel("Gradient")
plt.legend([plt.Rectangle((0,0),1,1,facecolor=c,alpha=0.6) for c in colors], labels)

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig("box_plot_gradient.png", dpi=200)
plt.show()
