#version 450

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 1, rgba32f) uniform image2D img;

layout(set = 0, binding = 25) buffer transformationBuffer { vec4 values[]; } transformation;

layout(set = 0, binding = 26) buffer baseTransformationBuffer { vec4 values[]; } baseTransformation;

uint getIndex(uvec3 x) { // for transformation only
    uint w = constants.binCount+1;
    return x.r + x.g * w + x.b * w * w;
}

layout(local_size_x = 16, local_size_y = 16) in;
void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    if (pixelCoords.x >= imageSize(img).x || pixelCoords.y >= imageSize(img).y) {
        return;
    }

    float maxBin = constants.binCount;
    vec4 color = imageLoad(img, pixelCoords);
    vec4 c = color * maxBin;

    float r0 = floor(c.x);
    float g0 = floor(c.y);
    float b0 = floor(c.z);
    float r1 = r0 + 1;
    float g1 = g0 + 1;
    float b1 = b0 + 1;

    float rd = c.x - r0;
    float gd = c.y - g0;
    float bd = c.z - b0;

    vec4 t000 = transformation.values[getIndex(uvec3(r0, g0, b0))] - baseTransformation.values[getIndex(uvec3(r0, g0, b0))];
    vec4 t001 = transformation.values[getIndex(uvec3(r0, g0, b1))] - baseTransformation.values[getIndex(uvec3(r0, g0, b1))];
    vec4 t010 = transformation.values[getIndex(uvec3(r0, g1, b0))] - baseTransformation.values[getIndex(uvec3(r0, g1, b0))];
    vec4 t011 = transformation.values[getIndex(uvec3(r0, g1, b1))] - baseTransformation.values[getIndex(uvec3(r0, g1, b1))];
    vec4 t100 = transformation.values[getIndex(uvec3(r1, g0, b0))] - baseTransformation.values[getIndex(uvec3(r1, g0, b0))];
    vec4 t101 = transformation.values[getIndex(uvec3(r1, g0, b1))] - baseTransformation.values[getIndex(uvec3(r1, g0, b1))];
    vec4 t110 = transformation.values[getIndex(uvec3(r1, g1, b0))] - baseTransformation.values[getIndex(uvec3(r1, g1, b0))];
    vec4 t111 = transformation.values[getIndex(uvec3(r1, g1, b1))] - baseTransformation.values[getIndex(uvec3(r1, g1, b1))];


    vec4 transf =
        t000 * (1-rd) * (1-gd) * (1-bd) +
        t001 * (1-rd) * (1-gd) * bd +
        t010 * (1-rd) * gd * (1-bd) +
        t011 * (1-rd) * gd * bd +
        t100 * rd * (1-gd) * (1-bd) +
        t101 * rd * (1-gd) * bd +
        t110 * rd * gd * (1-bd) +
        t111 * rd * gd * bd;

    color.xyz += transf.xyz;

    imageStore(img, pixelCoords, vec4(color.xyz, color.a));
    //imageStore(img, pixelCoords, vec4(1, 0, 1, color.a));
}
