#version 450

/*
Calculates the resulting transformation for every pixel of the image
with trilinear interpolation.
*/

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint bins;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 1, rgba32f) uniform image2D img;

layout(set = 0, binding = 18) buffer transformationBuffer { vec4 values[]; } transformation;

// calculated by the first dispatch
layout(set = 0, binding = 20) buffer uniformTransformationBuffer { vec4 values[]; } uniformTransformation;

uint getIndex(uvec3 x) { // for transformation only
    uint w = constants.bins+1;
    return x.r + x.g * w + x.b * w * w;
}

layout(local_size_x = 16, local_size_y = 16) in;
void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    if (pixelCoords.x >= imageSize(img).x || pixelCoords.y >= imageSize(img).y) {
        return;
    }

    float bins = constants.bins;
    vec4 color = imageLoad(img, pixelCoords);
    if(color.a == 0) return;
    vec4 c = color * bins;

    float r0 = clamp(floor(c.x), 0.0, bins - 1.0);
    float g0 = clamp(floor(c.y), 0.0, bins - 1.0);
    float b0 = clamp(floor(c.z), 0.0, bins - 1.0);
    float r1 = r0 + 1;
    float g1 = g0 + 1;
    float b1 = b0 + 1;

    float rd = c.x - r0;
    float gd = c.y - g0;
    float bd = c.z - b0;

    vec4 t000 = transformation.values[getIndex(uvec3(r0, g0, b0))] - uniformTransformation.values[getIndex(uvec3(r0, g0, b0))];
    vec4 t001 = transformation.values[getIndex(uvec3(r0, g0, b1))] - uniformTransformation.values[getIndex(uvec3(r0, g0, b1))];
    vec4 t010 = transformation.values[getIndex(uvec3(r0, g1, b0))] - uniformTransformation.values[getIndex(uvec3(r0, g1, b0))];
    vec4 t011 = transformation.values[getIndex(uvec3(r0, g1, b1))] - uniformTransformation.values[getIndex(uvec3(r0, g1, b1))];
    vec4 t100 = transformation.values[getIndex(uvec3(r1, g0, b0))] - uniformTransformation.values[getIndex(uvec3(r1, g0, b0))];
    vec4 t101 = transformation.values[getIndex(uvec3(r1, g0, b1))] - uniformTransformation.values[getIndex(uvec3(r1, g0, b1))];
    vec4 t110 = transformation.values[getIndex(uvec3(r1, g1, b0))] - uniformTransformation.values[getIndex(uvec3(r1, g1, b0))];
    vec4 t111 = transformation.values[getIndex(uvec3(r1, g1, b1))] - uniformTransformation.values[getIndex(uvec3(r1, g1, b1))];


    vec4 mapping =
        t000 * (1-rd) * (1-gd) * (1-bd) +
        t001 * (1-rd) * (1-gd) * bd +
        t010 * (1-rd) * gd * (1-bd) +
        t011 * (1-rd) * gd * bd +
        t100 * rd * (1-gd) * (1-bd) +
        t101 * rd * (1-gd) * bd +
        t110 * rd * gd * (1-bd) +
        t111 * rd * gd * bd;

    color.xyz += mapping.xyz;
    color = clamp(color, 0, 1);

    imageStore(img, pixelCoords, color);
    //imageStore(img, pixelCoords, vec4(1, 0, 1, color.a));
}
