#version 450

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
} constants;

layout(set = 0, binding = 1, rgba32f) uniform image2D img;

layout(set = 0, binding = 2) buffer HistogramBuffer {
    uint values[];
} histogram;

layout(local_size_x = 16, local_size_y = 16) in;
void main() {
    ivec2 pixelCoords = ivec2(gl_GlobalInvocationID.xy);
    if (pixelCoords.x >= imageSize(img).x || pixelCoords.y >= imageSize(img).y) {
        return;
    }

    vec3 color = imageLoad(img, pixelCoords).xyz;

    color *= float(constants.binCount);

    uint rBin = min(uint(floor(color.r)), constants.binCount - 1u);
    uint gBin = min(uint(floor(color.g)), constants.binCount - 1u);
    uint bBin = min(uint(floor(color.b)), constants.binCount - 1u);

    uint binIndex = rBin + gBin * constants.binCount + bBin * constants.binCount * constants.binCount;
    atomicAdd(histogram.values[binIndex], 1);
}
