#version 450

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 3) buffer KernelBuffer {
    float values[];
} kernelHistogram;

layout(set = 0, binding =  5) buffer integralBuffer000 { float values[]; } int000;
layout(set = 0, binding =  6) buffer integralBuffer001 { float values[]; } int001;
layout(set = 0, binding =  7) buffer integralBuffer010 { float values[]; } int010;
layout(set = 0, binding =  8) buffer integralBuffer011 { float values[]; } int011;
layout(set = 0, binding =  9) buffer integralBuffer100 { float values[]; } int100;
layout(set = 0, binding = 10) buffer integralBuffer101 { float values[]; } int101;
layout(set = 0, binding = 11) buffer integralBuffer110 { float values[]; } int110;
layout(set = 0, binding = 12) buffer integralBuffer111 { float values[]; } int111;
/*
layout(set = 0, binding = 13) buffer integralBufferX0 { float values[]; } intX0;
layout(set = 0, binding = 14) buffer integralBufferX1 { float values[]; } intX1;
layout(set = 0, binding = 15) buffer integralBufferY0 { float values[]; } intY0;
layout(set = 0, binding = 16) buffer integralBufferY1 { float values[]; } intY1;
layout(set = 0, binding = 17) buffer integralBufferZ0 { float values[]; } intZ0;
layout(set = 0, binding = 18) buffer integralBufferZ1 { float values[]; } intZ1;*/

uint getIndex(ivec3 x) {
    uint bins = constants.binCount;
    return x.r + x.g * bins + x.b * bins * bins;
}

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main() {
    uint binC = constants.binCount;
    ivec2 row = ivec2(gl_GlobalInvocationID.xy);
    if(any(greaterThanEqual(row, uvec2(uint(constants.binCount))))) return;

    uint index0 = getIndex(ivec3(0, row));
    uint index1 = getIndex(ivec3(binC-1, row));

    float sum0 = kernelHistogram.values[index0];
    float sum1 = kernelHistogram.values[index1];

    int000.values[index0] = sum0;
    int001.values[index0] = sum0;
    int010.values[index0] = sum0;
    int011.values[index0] = sum0;
    int100.values[index1] = sum1;
    int101.values[index1] = sum1;
    int110.values[index1] = sum1;
    int111.values[index1] = sum1;

    for(uint i = 1; i < binC; ++i) {
        index0 = getIndex(ivec3(i, row));
        index1 = getIndex(ivec3(binC-1 - i, row));
        sum0 += kernelHistogram.values[index0];
        sum1 += kernelHistogram.values[index1];

        int000.values[index0] = sum0;
        int001.values[index0] = sum0;
        int010.values[index0] = sum0;
        int011.values[index0] = sum0;
        int100.values[index1] = sum1;
        int101.values[index1] = sum1;
        int110.values[index1] = sum1;
        int111.values[index1] = sum1;
    }
}
