#version 450

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
} constants;

layout(set = 0, binding =  6) buffer integralBuffer000 { float values[]; } int000;
layout(set = 0, binding =  7) buffer integralBuffer001 { float values[]; } int001;
layout(set = 0, binding =  8) buffer integralBuffer010 { float values[]; } int010;
layout(set = 0, binding =  9) buffer integralBuffer011 { float values[]; } int011;
layout(set = 0, binding = 10) buffer integralBuffer100 { float values[]; } int100;
layout(set = 0, binding = 11) buffer integralBuffer101 { float values[]; } int101;
layout(set = 0, binding = 12) buffer integralBuffer110 { float values[]; } int110;
layout(set = 0, binding = 13) buffer integralBuffer111 { float values[]; } int111;

uint getIndex(ivec3 x) {
    uint bins = constants.binCount;
    return x.r + x.g * bins + x.b * bins * bins;
}

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main() {
    uint binC = constants.binCount;
    ivec2 row = ivec2(gl_GlobalInvocationID.xy);
    uint oldIndex0 = getIndex(ivec3(row.xy, 0));
    uint oldIndex1 = getIndex(ivec3(row.xy, binC-1));

    for(uint i = 1; i < binC; ++i) {
        uint index0 = getIndex(ivec3(row.xy, i));
        uint index1 = getIndex(ivec3(row.xy, binC-1-i));

        int000.values[index0] += int000.values[oldIndex0];
        int001.values[index1] += int001.values[oldIndex1];
        int010.values[index0] += int010.values[oldIndex0];
        int011.values[index1] += int011.values[oldIndex1];
        int100.values[index0] += int100.values[oldIndex0];
        int101.values[index1] += int101.values[oldIndex1];
        int110.values[index0] += int110.values[oldIndex0];
        int111.values[index1] += int111.values[oldIndex1];

        oldIndex0 = index0;
        oldIndex1 = index1;
    }
}
