#version 450

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 3) buffer KernelBuffer {
    float values[];
} kernelHistogram;

// Integrals
layout(set = 0, binding =  5) buffer integralBuffer000 { float values[]; } int000;
layout(set = 0, binding =  6) buffer integralBuffer001 { float values[]; } int001;
layout(set = 0, binding =  7) buffer integralBuffer010 { float values[]; } int010;
layout(set = 0, binding =  8) buffer integralBuffer011 { float values[]; } int011;
layout(set = 0, binding =  9) buffer integralBuffer100 { float values[]; } int100;
layout(set = 0, binding = 10) buffer integralBuffer101 { float values[]; } int101;
layout(set = 0, binding = 11) buffer integralBuffer110 { float values[]; } int110;
layout(set = 0, binding = 12) buffer integralBuffer111 { float values[]; } int111;

// Rotated Integrals
layout(set = 0, binding = 13) buffer integralBufferX0 { float values[]; } intX0;
layout(set = 0, binding = 14) buffer integralBufferX1 { float values[]; } intX1;
layout(set = 0, binding = 15) buffer integralBufferY0 { float values[]; } intY0;
layout(set = 0, binding = 16) buffer integralBufferY1 { float values[]; } intY1;
layout(set = 0, binding = 17) buffer integralBufferZ0 { float values[]; } intZ0;
layout(set = 0, binding = 18) buffer integralBufferZ1 { float values[]; } intZ1;

uint getIndex(ivec3 x) {
    uint bins = constants.binCount;
    return x.r + x.g * bins + x.b * bins * bins;
}

layout(local_size_x = 32, local_size_y = 32, local_size_z = 1) in;
void main() {
    uint binC = constants.binCount;
    ivec2 row = ivec2(gl_GlobalInvocationID.xy);
    if(any(greaterThanEqual(row, ivec2(binC)))) return;

    // Normal integrals
    uint index0 = getIndex(ivec3(0, row));
    uint index1 = getIndex(ivec3(binC-1, row));

    float sum0 = kernelHistogram.values[index0];
    float sum1 = kernelHistogram.values[index1];

    int000.values[index0] = sum0;
    int001.values[index0] = sum0;
    int010.values[index0] = sum0;
    int011.values[index0] = sum0;
    int100.values[index1] = sum1;
    int101.values[index1] = sum1;
    int110.values[index1] = sum1;
    int111.values[index1] = sum1;

    // Columns for rotated integrals
    intX0.values[index0] = kernelHistogram.values[index0];
    intX1.values[index1] = kernelHistogram.values[index1];
    intY0.values[getIndex(ivec3(row.x, 0, row.y))] = kernelHistogram.values[getIndex(ivec3(row.x, 0, row.y))];
    intY1.values[getIndex(ivec3(row.x, binC-1, row.y))] = kernelHistogram.values[getIndex(ivec3(row.x, binC-1, row.y))];
    intZ0.values[getIndex(ivec3(row, 0))] = kernelHistogram.values[getIndex(ivec3(row, 0))];
    intZ1.values[getIndex(ivec3(row, binC-1))] = kernelHistogram.values[getIndex(ivec3(row, binC-1))];

    for(uint i = 1; i < binC; ++i) {
        // Normal integrals
        index0 = getIndex(ivec3(i, row));
        index1 = getIndex(ivec3(binC-1 - i, row));
        sum0 += kernelHistogram.values[index0];
        sum1 += kernelHistogram.values[index1];

        int000.values[index0] = sum0;
        int001.values[index0] = sum0;
        int010.values[index0] = sum0;
        int011.values[index0] = sum0;
        int100.values[index1] = sum1;
        int101.values[index1] = sum1;
        int110.values[index1] = sum1;
        int111.values[index1] = sum1;

        // Columns for rotated integrals
        uint iX0 = getIndex(ivec3(i, row));
        uint iX1 = getIndex(ivec3(binC-1-i, row));
        uint iY0 = getIndex(ivec3(row.x, i, row.y));
        uint iY1 = getIndex(ivec3(row.x, binC-1-i, row.y));
        uint iZ0 = getIndex(ivec3(row, i));
        uint iZ1 = getIndex(ivec3(row, binC-1-i));

        intX0.values[iX0] = intX0.values[getIndex(ivec3(i-1, row))] + kernelHistogram.values[iX0];
        intX1.values[iX1] = intX1.values[getIndex(ivec3(binC-i, row))] + kernelHistogram.values[iX1];
        intY0.values[iY0] = intY0.values[getIndex(ivec3(row.x, i-1, row.y))] + kernelHistogram.values[iY0];
        intY1.values[iY1] = intY1.values[getIndex(ivec3(row.x, binC-i, row.y))] + kernelHistogram.values[iY1];
        intZ0.values[iZ0] = intZ0.values[getIndex(ivec3(row, i-1))] + kernelHistogram.values[iZ0];
        intZ1.values[iZ1] = intZ1.values[getIndex(ivec3(row, binC-i))] + kernelHistogram.values[iZ1];
    }
}
