#version 450

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 2) buffer HistogramBuffer {
    uint values[];
} histogram;

layout(set = 0, binding = 3) buffer KernelBuffer {
    float values[];
} kernelHistogram;

layout(set = 0, binding = 4) buffer GaussLookUpBuffer {
    float values[];
} gauss;

int getIndex(ivec3 x) {
    int bins = int(constants.binCount);
    if(any(lessThan(x, ivec3(0)))) return -1;
    if(any(greaterThanEqual(x, ivec3(bins)))) return -1;
    return x.r + x.g * bins + x.b * bins * bins;
}

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main() {
    ivec3 color = ivec3(gl_GlobalInvocationID.xyz);
    if(any(greaterThanEqual(color, ivec3(int(constants.binCount))))) return;

    int radius = int(constants.radius);
    float sum = 0;
    float weight = 0;
    
    uint size = constants.radius * 2 + 1;
    for (int z = -radius; z <= radius; ++z) {
        for (int y = -radius; y <= radius; ++y) {
            for (int x = -radius; x <= radius; ++x) {
                int neighborIndex = int(getIndex(color + ivec3(x, y, z)));
                if(neighborIndex == -1) continue;

                uint weightIndex = (z + radius) * size * size + (y + radius) * size + (x + radius);
                sum += histogram.values[neighborIndex] * gauss.values[weightIndex];
                weight += gauss.values[weightIndex];
            }
        }
    }
    sum /= weight;
    kernelHistogram.values[getIndex(color)] = constants.d0 + sum;
}
