#version 450

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
} constants;

layout(set = 0, binding = 2) buffer HistogramBuffer {
    uint values[];
} histogram;

layout(set = 0, binding = 3) buffer KernelBuffer {
    uint values[];
} kernelHistogram;

layout(set = 0, binding = 4) buffer GaussLookUpBuffer {
    float values[];
} gauss;

uint getIndex(ivec3 x) {
    uint bins = constants.binCount;
    return x.r + x.g * bins + x.b * bins * bins;
}

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main() {
    ivec3 color = ivec3(gl_GlobalInvocationID.xyz);
    if(any(greaterThanEqual(color, ivec3(int(constants.binCount))))) return;

    int radius = int(constants.radius);
    float sum = 0;
    float weight = 0;
    
    for(int i = -radius; i <= radius; i++) {
        int neighborIndex = color.g+i;
        if(neighborIndex < 0 || neighborIndex >= int(constants.binCount)) continue;
        sum += kernelHistogram.values[getIndex(ivec3(color.r, neighborIndex, color.b))] * gauss.values[i+radius];
        weight += gauss.values[i+radius];
    }
    sum /= weight;
    histogram.values[getIndex(color)] = uint(sum);
}
