#version 450

/*
There is one more transformation than histogram bins for each dimension. 
They correspond to the transformations of the corners around the histogram bins.

(2D example:)

t[0][0]          t[1][0] ...

        h[0][0]          ...

t[0][1]          t[1][1] ...
...              ...
*/

#define USE_NORMAL_INT 1
#define USE_ROTATED_INT 0
#define USE_NORMAL_ANCHOR 1

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint bins;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 2) buffer HistogramBuffer {
    uint values[];
} histogram;

layout(set = 0, binding =  5) buffer integralBuffer { float values[]; } integral;

// Rotated integrals
layout(set = 0, binding = 6) buffer integralBufferX0 { float values[]; } intX0;
layout(set = 0, binding = 7) buffer integralBufferX1 { float values[]; } intX1;
layout(set = 0, binding = 8) buffer integralBufferY0 { float values[]; } intY0;
layout(set = 0, binding = 9) buffer integralBufferY1 { float values[]; } intY1;
layout(set = 0, binding = 10) buffer integralBufferZ0 { float values[]; } intZ0;
layout(set = 0, binding = 11) buffer integralBufferZ1 { float values[]; } intZ1;

// Temp buffer for rotated integrals
layout(set = 0, binding = 12) buffer tempIntBufferX0 { float values[]; } tempX0;
layout(set = 0, binding = 13) buffer tempIntBufferX1 { float values[]; } tempX1;
layout(set = 0, binding = 14) buffer tempIntBufferY0 { float values[]; } tempY0;
layout(set = 0, binding = 15) buffer tempIntBufferY1 { float values[]; } tempY1;
layout(set = 0, binding = 16) buffer tempIntBufferZ0 { float values[]; } tempZ0;
layout(set = 0, binding = 17) buffer tempIntBufferZ1 { float values[]; } tempZ1;

layout(set = 0, binding = 18, std140) buffer transformationBuffer { vec4 values[]; } transformation;

int getIndex(ivec3 x) {
    int bins = int(constants.bins);
    if(any(lessThan(x, ivec3(0)))) return -1;
    if(any(greaterThanEqual(x, ivec3(bins)))) return -1;
    return x.r + x.g * bins + x.b * bins * bins;
}

int getIndexTemp(int n, ivec3 x) {
    int bins = int(constants.bins);
    if(any(lessThan(x, ivec3(0)))) return -1;
    if(any(greaterThanEqual(x, ivec3(bins)))) return -1;
    return getIndex(x) + n * bins * bins * bins;
}

float getIntegralAt(int x, int y, int z) {
    int index = getIndex(ivec3(x, y, z));
    return index == -1 ? 0 : integral.values[index];
}

// anchor point calculation for point p in the direction d 
#if USE_NORMAL_ANCHOR
vec3 anchor(vec3 p, vec3 d) {
    vec3 tmax;
    tmax.x = (d.x > 0.0) ? (1.0 - p.x)/d.x : (0.0 - p.x)/d.x;
    tmax.y = (d.y > 0.0) ? (1.0 - p.y)/d.y : (0.0 - p.y)/d.y;
    tmax.z = (d.z > 0.0) ? (1.0 - p.z)/d.z : (0.0 - p.z)/d.z;
    float t = min(tmax.x, min(tmax.y, tmax.z));
    return p + t * d;
}
#else
vec3 anchor(vec3 p, vec3 d) {
    float eps = 1e-12;

    float tx = (abs(d.x) > eps) 
        ? ((d.x > 0.0) ? (1.0 - p.x) / d.x : (0.0 - p.x) / d.x)
        : 1e30;

    float ty = (abs(d.y) > eps) 
        ? ((d.y > 0.0) ? (1.0 - p.y) / d.y : (0.0 - p.y) / d.y)
        : 1e30;

    float tz = (abs(d.z) > eps) 
        ? ((d.z > 0.0) ? (1.0 - p.z) / d.z : (0.0 - p.z) / d.z)
        : 1e30;

    float t = min(tx, min(ty, tz));

    vec3 result = p + d * t;

    return clamp(result, 0.0, 1.0);
}
#endif

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main() {
    float binsFloat = constants.bins;
    int bins = int(constants.bins);

    ivec3 color = ivec3(gl_GlobalInvocationID.xyz);
    if(any(greaterThan(color, ivec3(bins)))) return;

    float x = color.x / binsFloat;
    float y = color.y / binsFloat;
    float z = color.z / binsFloat;
    int i = color.x;
    int j = color.y;
    int k = color.z;
    vec3 p = vec3(x, y, z);

    // Anchor Points (q000 is opposite of (0,0,0) )

#if USE_NORMAL_ANCHOR
    vec3 q000 = anchor(p, vec3( 1, 1, 1));
    vec3 q001 = anchor(p, vec3( 1, 1,-1));
    vec3 q010 = anchor(p, vec3( 1,-1, 1));
    vec3 q011 = anchor(p, vec3( 1,-1,-1));
    vec3 q100 = anchor(p, vec3(-1, 1, 1));
    vec3 q101 = anchor(p, vec3(-1, 1,-1));
    vec3 q110 = anchor(p, vec3(-1,-1, 1));
    vec3 q111 = anchor(p, vec3(-1,-1,-1));
#else
    vec3 q000 = anchor(p, (vec3(p.x, p.y, p.z)));
    vec3 q001 = anchor(p, (vec3(p.x, p.y, p.z-1)));
    vec3 q010 = anchor(p, (vec3(p.x, p.y-1, p.z)));
    vec3 q011 = anchor(p, (vec3(p.x, p.y-1, p.z-1)));
    vec3 q100 = anchor(p, (vec3(p.x-1, p.y, p.z)));
    vec3 q101 = anchor(p, (vec3(p.x-1, p.y, p.z-1)));
    vec3 q110 = anchor(p, (vec3(p.x-1, p.y-1, p.z)));
    vec3 q111 = anchor(p, (vec3(p.x-1, p.y-1, p.z-1)));
#endif

    float max_x = getIntegralAt(bins-1, j-1, k-1);
    float max_y = getIntegralAt(i-1, bins-1, k-1);
    float max_z = getIntegralAt(i-1, j-1, bins-1);
    float max_xy = getIntegralAt(bins-1, bins-1, k-1);
    float max_yz = getIntegralAt(i-1, bins-1, bins-1);
    float max_xz = getIntegralAt(bins-1, j-1, bins-1);
    float max_xyz = getIntegralAt(bins-1, bins-1, bins-1);


    float weight000 = getIntegralAt(i-1, j-1, k-1);

    float weight100 = max_x - weight000;
    float weight010 = max_y - weight000;
    float weight001 = max_z - weight000;

    float weight110 = max_xy - max_x - max_y + weight000;
    float weight011 = max_yz - max_y - max_z + weight000;
    float weight101 = max_xz - max_x - max_z + weight000;

    float weight111 = max_xyz - max_xy - max_yz - max_xz + max_x + max_y + max_z - weight000;

#if USE_ROTATED_INT
    ivec3 id000 = ivec3(i-1, j-1, k-1);
    ivec3 id001 = ivec3(i-1, j-1, k);
    ivec3 id010 = ivec3(i-1, j, k-1);
    ivec3 id011 = ivec3(i-1, j, k);
    ivec3 id100 = ivec3(i, j-1, k-1);
    ivec3 id101 = ivec3(i, j-1, k);
    ivec3 id110 = ivec3(i, j, k-1);
    ivec3 id111 = ivec3(i, j, k);

    float weightX0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempX0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id001) == -1 ? 0 : tempX0.values[getIndexTemp(1, id001)])
        + (getIndexTemp(2, id010) == -1 ? 0 : tempX0.values[getIndexTemp(2, id010)])
        + (getIndexTemp(3, id011) == -1 ? 0 : tempX0.values[getIndexTemp(3, id011)]);
    
    float weightX1
        = (getIndexTemp(0, id100) == -1 ? 0 : tempX1.values[getIndexTemp(0, id100)])
        + (getIndexTemp(1, id101) == -1 ? 0 : tempX1.values[getIndexTemp(1, id101)])
        + (getIndexTemp(2, id110) == -1 ? 0 : tempX1.values[getIndexTemp(2, id110)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempX1.values[getIndexTemp(3, id111)]);
    
    float weightY0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempY0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id001) == -1 ? 0 : tempY0.values[getIndexTemp(1, id001)])
        + (getIndexTemp(2, id100) == -1 ? 0 : tempY0.values[getIndexTemp(2, id100)])
        + (getIndexTemp(3, id101) == -1 ? 0 : tempY0.values[getIndexTemp(3, id101)]);
    
    float weightY1
        = (getIndexTemp(0, id010) == -1 ? 0 : tempY1.values[getIndexTemp(0, id010)])
        + (getIndexTemp(1, id011) == -1 ? 0 : tempY1.values[getIndexTemp(1, id011)])
        + (getIndexTemp(2, id110) == -1 ? 0 : tempY1.values[getIndexTemp(2, id110)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempY1.values[getIndexTemp(3, id111)]);
    
    float weightZ0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempZ0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id010) == -1 ? 0 : tempZ0.values[getIndexTemp(1, id010)])
        + (getIndexTemp(2, id100) == -1 ? 0 : tempZ0.values[getIndexTemp(2, id100)])
        + (getIndexTemp(3, id110) == -1 ? 0 : tempZ0.values[getIndexTemp(3, id110)]);
    
    float weightZ1
        = (getIndexTemp(0, id001) == -1 ? 0 : tempZ1.values[getIndexTemp(0, id001)])
        + (getIndexTemp(1, id011) == -1 ? 0 : tempZ1.values[getIndexTemp(1, id011)])
        + (getIndexTemp(2, id101) == -1 ? 0 : tempZ1.values[getIndexTemp(2, id101)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempZ1.values[getIndexTemp(3, id111)]);
#endif

    float sumWeights = 0; // sumWeights is mainly for debugging purposes. It should equal int111.values[0]

#if USE_NORMAL_INT
    sumWeights += weight000 + weight001 + weight010 + weight011 + weight100 + weight101 + weight110 + weight111;
#endif
#if USE_ROTATED_INT
    sumWeights += weightX0 + weightX1 + weightY0 + weightY1 + weightZ0 + weightZ1;
#endif

    vec3 map = vec3(0);

#if USE_NORMAL_INT
    map += 
      q000 * weight000
    + q001 * weight001
    + q010 * weight010
    + q011 * weight011
    + q100 * weight100
    + q101 * weight101
    + q110 * weight110
    + q111 * weight111;
#endif

#if USE_ROTATED_INT
    map += vec3(1, y, z) * weightX0
    + vec3(0, y, z) * weightX1
    + vec3(x, 1, z) * weightY0
    + vec3(x, 0, z) * weightY1
    + vec3(x, y, 1) * weightZ0
    + vec3(x, y, 0) * weightZ1;

    if(any(lessThan(ivec3(color), ivec3(maxBin))) && any(greaterThanEqual(ivec3(color), ivec3(0)))) { // only for debugging right now
        intX0.values[getIndex(ivec3(i, j, k))] = weightX0; 
        intX1.values[getIndex(ivec3(i, j, k))] = weightX1;
        intY0.values[getIndex(ivec3(i, j, k))] = weightY0;
        intY1.values[getIndex(ivec3(i, j, k))] = weightY1;
        intZ0.values[getIndex(ivec3(i, j, k))] = weightZ0;
        intZ1.values[getIndex(ivec3(i, j, k))] = weightZ1;
    }
#endif

    map /= max_xyz;

    uint bin1 = bins+1; // there are (bins+1)^3 transformations
    uint trIndex = 
        uint(i + j * bin1 + k * bin1 * bin1); 
    transformation.values[trIndex] = vec4(map, 0);

    if(any(lessThan(ivec3(color), ivec3(bins)))) // clear accumulation histogram for next iteration
        histogram.values[getIndex(color)] = 0;
}
