#version 450

#define USE_NORMAL_INT true
#define USE_ROTATED_INT false

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 2) buffer HistogramBuffer {
    uint values[];
} histogram;

layout(set = 0, binding =  5) buffer integralBuffer000 { float values[]; } int000;
layout(set = 0, binding =  6) buffer integralBuffer001 { float values[]; } int001;
layout(set = 0, binding =  7) buffer integralBuffer010 { float values[]; } int010;
layout(set = 0, binding =  8) buffer integralBuffer011 { float values[]; } int011;
layout(set = 0, binding =  9) buffer integralBuffer100 { float values[]; } int100;
layout(set = 0, binding = 10) buffer integralBuffer101 { float values[]; } int101;
layout(set = 0, binding = 11) buffer integralBuffer110 { float values[]; } int110;
layout(set = 0, binding = 12) buffer integralBuffer111 { float values[]; } int111;

layout(set = 0, binding = 13) buffer integralBufferX0 { float values[]; } intX0;
layout(set = 0, binding = 14) buffer integralBufferX1 { float values[]; } intX1;
layout(set = 0, binding = 15) buffer integralBufferY0 { float values[]; } intY0;
layout(set = 0, binding = 16) buffer integralBufferY1 { float values[]; } intY1;
layout(set = 0, binding = 17) buffer integralBufferZ0 { float values[]; } intZ0;
layout(set = 0, binding = 18) buffer integralBufferZ1 { float values[]; } intZ1;

layout(set = 0, binding = 19) buffer tempIntBufferX0 { float values[]; } tempX0;
layout(set = 0, binding = 20) buffer tempIntBufferX1 { float values[]; } tempX1;
layout(set = 0, binding = 21) buffer tempIntBufferY0 { float values[]; } tempY0;
layout(set = 0, binding = 22) buffer tempIntBufferY1 { float values[]; } tempY1;
layout(set = 0, binding = 23) buffer tempIntBufferZ0 { float values[]; } tempZ0;
layout(set = 0, binding = 24) buffer tempIntBufferZ1 { float values[]; } tempZ1;

layout(set = 0, binding = 25, std140) buffer transformationBuffer { vec4 values[]; } transformation;

int getIndex(ivec3 x) { // For integrals!
    int bins = int(constants.binCount);
    if(any(lessThan(x, ivec3(0)))) return -1;
    if(any(greaterThanEqual(x, ivec3(bins)))) return -1;
    return x.r + x.g * bins + x.b * bins * bins;
}

int getIndexTemp(int n, ivec3 x) {
    int bins = int(constants.binCount);
    if(any(lessThan(x, ivec3(0)))) return -1;
    if(any(greaterThanEqual(x, ivec3(bins)))) return -1;
    return getIndex(x) + n * bins * bins * bins;
}

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main() {
    float maxBin = constants.binCount;

    ivec3 color = ivec3(gl_GlobalInvocationID.xyz);
    if(any(greaterThan(color, uvec3(uint(constants.binCount))))) return;

    vec3 q000, q001, q010, q011, q100, q101, q110, q111;
    float x = color.x / float(maxBin);
    float y = color.y / float(maxBin);
    float z = color.z / float(maxBin);
    int i = color.x;
    int j = color.y;
    int k = color.z;

    // q000
    if (i <= j && i <= k) {
        q000 = vec3(0, y - x, z - x);
    } else if (j <= i && j <= k) {
        q000 = vec3(x - y, 0, z - y);
    } else {
        q000 = vec3(x - z, y - z, 0);
    }

    // q001
    if (i <= j && i <= (maxBin - k)) {
        q001 = vec3(0, y - x, z + x);
    } else if (j <= i && j <= (maxBin - k)) {
        q001 = vec3(x - y, 0, z + y);
    } else {
        q001 = vec3(x + z - 1, y + z - 1, 1);
    }

    // q010
    if (i <= (maxBin - j) && i <= k) {
        q010 = vec3(0, x + y, z - x);
    } else if ((maxBin - j) <= i && (maxBin - j) <= k) {
        q010 = vec3(x + y - 1, 1, y + z - 1);
    } else {
        q010 = vec3(x - z, y + z, 0);
    }

    // q011
    if (i <= (maxBin - j) && i <= (maxBin - k)) {
        q011 = vec3(0, x + y, x + z);
    } else if ((maxBin - j) <= i && (maxBin - j) <= (maxBin - k)) {
        q011 = vec3(x + y - 1, 1, z - y + 1);
    } else {
        q011 = vec3(x + z - 1, y - z + 1, 1);
    }

    // q100
    if ((maxBin - i) <= j && (maxBin - i) <= k) {
        q100 = vec3(1, x + y - 1, x + z - 1);
    } else if (j <= (maxBin - i) && j <= k) {
        q100 = vec3(x + y, 0, z - y);
    } else {
        q100 = vec3(x + z, y - z, 0);
    }

    // q101
    if ((maxBin - i) <= j && (maxBin - i) <= (maxBin - k)) {
        q101 = vec3(1, x + y - 1, z - x + 1);
    } else if (j <= (maxBin - i) && j <= (maxBin - k)) {
        q101 = vec3(x + y, 0, y + z);
    } else {
        q101 = vec3(x - z + 1, y + z - 1, 1);
    }

    // q110
    if ((maxBin - i) <= (maxBin - j) && (maxBin - i) <= k) {
        q110 = vec3(1, y - x + 1, z + x - 1);
    } else if ((maxBin - j) <= (maxBin - i) && (maxBin - j) <= k) {
        q110 = vec3(x - y + 1, 1, z + y - 1);
    } else {
        q110 = vec3(x + z, y + z, 0);
    }

    // q111
    if ((maxBin - i) <= (maxBin - j) && (maxBin - i) <= (maxBin - k)) {
        q111 = vec3(1, y - x + 1, z - x + 1);
    } else if ((maxBin - j) <= (maxBin - i) && (maxBin - j) <= (maxBin - k)) {
        q111 = vec3(x - y + 1, 1, z - y + 1);
    } else {
        q111 = vec3(x - z + 1, y - z + 1, 1);
    }

    /*uint index = getIndex(color);
    float weight000 = int000.values[index];
    float weight001 = int001.values[index];
    float weight010 = int010.values[index];
    float weight011 = int011.values[index];
    float weight100 = int100.values[index];
    float weight101 = int101.values[index];
    float weight110 = int110.values[index];
    float weight111 = int111.values[index];*/

    int index000 = getIndex(ivec3(i-1, j-1, k-1));
    float weight000 = index000 == -1 ? 0 :  int000.values[index000];

    int index001 = getIndex(ivec3(i-1, j-1, k));
    float weight001 = index001 == -1 ? 0 :  int001.values[index001];

    int index010 = getIndex(ivec3(i-1, j, k-1));
    float weight010 = index010 == -1 ? 0 :  int010.values[index010];

    int index011 = getIndex(ivec3(i-1, j, k));
    float weight011 = index011 == -1 ? 0 :  int011.values[index011];

    int index100 = getIndex(ivec3(i, j-1, k-1));
    float weight100 = index100 == -1 ? 0 :  int100.values[index100];

    int index101 = getIndex(ivec3(i, j-1, k));
    float weight101 = index101 == -1 ? 0 :  int101.values[index101];

    int index110 = getIndex(ivec3(i, j, k-1));
    float weight110 = index110 == -1 ? 0 :  int110.values[index110];

    int index111 = getIndex(ivec3(i, j, k));
    float weight111 = index111 == -1 ? 0 :  int111.values[index111];

    ivec3 id000 = ivec3(i-1, j-1, k-1);
    ivec3 id001 = ivec3(i-1, j-1, k);
    ivec3 id010 = ivec3(i-1, j, k-1);
    ivec3 id011 = ivec3(i-1, j, k);

    ivec3  id100 = ivec3(i, j-1, k-1);
    ivec3  id101 = ivec3(i, j-1, k);
    ivec3  id110 = ivec3(i, j, k-1);
    ivec3  id111 = ivec3(i, j, k);

    float weightX0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempX0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id001) == -1 ? 0 : tempX0.values[getIndexTemp(1, id001)])
        + (getIndexTemp(2, id010) == -1 ? 0 : tempX0.values[getIndexTemp(2, id010)])
        + (getIndexTemp(3, id011) == -1 ? 0 : tempX0.values[getIndexTemp(3, id011)]);
    
    float weightX1
        = (getIndexTemp(0, id100) == -1 ? 0 : tempX1.values[getIndexTemp(0, id100)])
        + (getIndexTemp(1, id101) == -1 ? 0 : tempX1.values[getIndexTemp(1, id101)])
        + (getIndexTemp(2, id110) == -1 ? 0 : tempX1.values[getIndexTemp(2, id110)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempX1.values[getIndexTemp(3, id111)]);
    
    float weightY0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempY0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id001) == -1 ? 0 : tempY0.values[getIndexTemp(1, id001)])
        + (getIndexTemp(2, id100) == -1 ? 0 : tempY0.values[getIndexTemp(2, id100)])
        + (getIndexTemp(3, id101) == -1 ? 0 : tempY0.values[getIndexTemp(3, id101)]);
    
    float weightY1
        = (getIndexTemp(0, id010) == -1 ? 0 : tempY1.values[getIndexTemp(0, id010)])
        + (getIndexTemp(1, id011) == -1 ? 0 : tempY1.values[getIndexTemp(1, id011)])
        + (getIndexTemp(2, id110) == -1 ? 0 : tempY1.values[getIndexTemp(2, id110)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempY1.values[getIndexTemp(3, id111)]);
    
    float weightZ0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempZ0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id010) == -1 ? 0 : tempZ0.values[getIndexTemp(1, id010)])
        + (getIndexTemp(2, id100) == -1 ? 0 : tempZ0.values[getIndexTemp(2, id100)])
        + (getIndexTemp(3, id110) == -1 ? 0 : tempZ0.values[getIndexTemp(3, id110)]);
    
    float weightZ1
        = (getIndexTemp(0, id001) == -1 ? 0 : tempZ1.values[getIndexTemp(0, id001)])
        + (getIndexTemp(1, id011) == -1 ? 0 : tempZ1.values[getIndexTemp(1, id011)])
        + (getIndexTemp(2, id101) == -1 ? 0 : tempZ1.values[getIndexTemp(2, id101)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempZ1.values[getIndexTemp(3, id111)]);
    
    float sumWeights = 0;
    if(USE_NORMAL_INT)
        sumWeights += weight000 + weight001 + weight010 + weight011 + weight100 + weight101 + weight110 + weight111;
    
    if(USE_ROTATED_INT)
        sumWeights += weightX0 + weightX1 + weightY0 + weightY1 + weightZ0 + weightZ1;

    vec3 map = vec3(0);
        
    if(USE_NORMAL_INT)
        map += q111 * weight000
        + q110 * weight001
        + q101 * weight010
        + q100 * weight011
        + q011 * weight100
        + q010 * weight101
        + q001 * weight110
        + q000 * weight111;
    
    if(USE_ROTATED_INT)
        map += vec3(1, y, z) * weightX0
        + vec3(0, y, z) * weightX1
        + vec3(x, 1, z) * weightY0
        + vec3(x, 0, z) * weightY1
        + vec3(x, y, 1) * weightZ0
        + vec3(x, y, 0) * weightZ1;

    if(any(lessThan(ivec3(color), ivec3(maxBin))) && any(greaterThanEqual(ivec3(color), ivec3(0)))) { // only for debugging right now
        intX0.values[getIndex(ivec3(i, j, k))] = weightX0; 
        intX1.values[getIndex(ivec3(i, j, k))] = weightX1;
        intY0.values[getIndex(ivec3(i, j, k))] = weightY0;
        intY1.values[getIndex(ivec3(i, j, k))] = weightY1;
        intZ0.values[getIndex(ivec3(i, j, k))] = weightZ0;
        intZ1.values[getIndex(ivec3(i, j, k))] = weightZ1;
    }

    map *= float(maxBin) / sumWeights;
    uint trIndex = 
        uint(i + j * (maxBin+1) + k * (maxBin+1) * (maxBin+1)); 
    transformation.values[trIndex] = vec4(map, 0);

    if(any(lessThan(ivec3(color), ivec3(maxBin))))
        histogram.values[getIndex(color)] = 0;
}
