#version 450

#define USE_NORMAL_INT 1
#define USE_ROTATED_INT 0

layout(set = 0, binding = 0) uniform UniformBuffer {
    uint binCount;
    uint radius;
    float d0;
} constants;

layout(set = 0, binding = 2) buffer HistogramBuffer {
    uint values[];
} histogram;

layout(set = 0, binding =  5) buffer integralBuffer000 { float values[]; } int000;
layout(set = 0, binding =  6) buffer integralBuffer001 { float values[]; } int001;
layout(set = 0, binding =  7) buffer integralBuffer010 { float values[]; } int010;
layout(set = 0, binding =  8) buffer integralBuffer011 { float values[]; } int011;
layout(set = 0, binding =  9) buffer integralBuffer100 { float values[]; } int100;
layout(set = 0, binding = 10) buffer integralBuffer101 { float values[]; } int101;
layout(set = 0, binding = 11) buffer integralBuffer110 { float values[]; } int110;
layout(set = 0, binding = 12) buffer integralBuffer111 { float values[]; } int111;

layout(set = 0, binding = 13) buffer integralBufferX0 { float values[]; } intX0;
layout(set = 0, binding = 14) buffer integralBufferX1 { float values[]; } intX1;
layout(set = 0, binding = 15) buffer integralBufferY0 { float values[]; } intY0;
layout(set = 0, binding = 16) buffer integralBufferY1 { float values[]; } intY1;
layout(set = 0, binding = 17) buffer integralBufferZ0 { float values[]; } intZ0;
layout(set = 0, binding = 18) buffer integralBufferZ1 { float values[]; } intZ1;

layout(set = 0, binding = 19) buffer tempIntBufferX0 { float values[]; } tempX0;
layout(set = 0, binding = 20) buffer tempIntBufferX1 { float values[]; } tempX1;
layout(set = 0, binding = 21) buffer tempIntBufferY0 { float values[]; } tempY0;
layout(set = 0, binding = 22) buffer tempIntBufferY1 { float values[]; } tempY1;
layout(set = 0, binding = 23) buffer tempIntBufferZ0 { float values[]; } tempZ0;
layout(set = 0, binding = 24) buffer tempIntBufferZ1 { float values[]; } tempZ1;

layout(set = 0, binding = 25, std140) buffer transformationBuffer { vec4 values[]; } transformation;

int getIndex(ivec3 x) {
    int bins = int(constants.binCount);
    if(any(lessThan(x, ivec3(0)))) return -1;
    if(any(greaterThanEqual(x, ivec3(bins)))) return -1;
    return x.r + x.g * bins + x.b * bins * bins;
}

int getIndexTemp(int n, ivec3 x) {
    int bins = int(constants.binCount);
    if(any(lessThan(x, ivec3(0)))) return -1;
    if(any(greaterThanEqual(x, ivec3(bins)))) return -1;
    return getIndex(x) + n * bins * bins * bins;
}

vec3 anchor(vec3 p, vec3 d) {
    vec3 tmax;
    tmax.x = (d.x > 0.0) ? (1.0 - p.x)/d.x : (0.0 - p.x)/d.x;
    tmax.y = (d.y > 0.0) ? (1.0 - p.y)/d.y : (0.0 - p.y)/d.y;
    tmax.z = (d.z > 0.0) ? (1.0 - p.z)/d.z : (0.0 - p.z)/d.z;
    float t = min(tmax.x, min(tmax.y, tmax.z));
    return p + t * d;
}

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main() {
    float maxBin = constants.binCount;

    ivec3 color = ivec3(gl_GlobalInvocationID.xyz);
    if(any(greaterThan(color, ivec3(maxBin)))) return;

    float x = color.x / float(maxBin);
    float y = color.y / float(maxBin);
    float z = color.z / float(maxBin);
    int i = color.x;
    int j = color.y;
    int k = color.z;
    vec3 p = vec3(x, y, z);

    // q000
    vec3 q000 = anchor(p, vec3(-1,-1,-1));
    vec3 q001 = anchor(p, vec3(-1,-1, 1));
    vec3 q010 = anchor(p, vec3(-1, 1,-1));
    vec3 q011 = anchor(p, vec3(-1, 1, 1));
    vec3 q100 = anchor(p, vec3( 1,-1,-1));
    vec3 q101 = anchor(p, vec3( 1,-1, 1));
    vec3 q110 = anchor(p, vec3( 1, 1,-1));
    vec3 q111 = anchor(p, vec3( 1, 1, 1));


    int index000 = getIndex(ivec3(i-1, j-1, k-1));
    int index001 = getIndex(ivec3(i-1, j-1, k));
    int index010 = getIndex(ivec3(i-1, j, k-1));
    int index011 = getIndex(ivec3(i-1, j, k));
    int index100 = getIndex(ivec3(i, j-1, k-1));
    int index101 = getIndex(ivec3(i, j-1, k));
    int index110 = getIndex(ivec3(i, j, k-1));
    int index111 = getIndex(ivec3(i, j, k));

    float weight000 = index000 == -1 ? 0 :  int000.values[index000];
    float weight001 = index001 == -1 ? 0 :  int001.values[index001];
    float weight010 = index010 == -1 ? 0 :  int010.values[index010];
    float weight011 = index011 == -1 ? 0 :  int011.values[index011];
    float weight100 = index100 == -1 ? 0 :  int100.values[index100];
    float weight101 = index101 == -1 ? 0 :  int101.values[index101];
    float weight110 = index110 == -1 ? 0 :  int110.values[index110];
    float weight111 = index111 == -1 ? 0 :  int111.values[index111];

    ivec3 id000 = ivec3(i-1, j-1, k-1);
    ivec3 id001 = ivec3(i-1, j-1, k);
    ivec3 id010 = ivec3(i-1, j, k-1);
    ivec3 id011 = ivec3(i-1, j, k);

    ivec3  id100 = ivec3(i, j-1, k-1);
    ivec3  id101 = ivec3(i, j-1, k);
    ivec3  id110 = ivec3(i, j, k-1);
    ivec3  id111 = ivec3(i, j, k);

#if USE_ROTATED_INT
    float weightX0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempX0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id001) == -1 ? 0 : tempX0.values[getIndexTemp(1, id001)])
        + (getIndexTemp(2, id010) == -1 ? 0 : tempX0.values[getIndexTemp(2, id010)])
        + (getIndexTemp(3, id011) == -1 ? 0 : tempX0.values[getIndexTemp(3, id011)]);
    
    float weightX1
        = (getIndexTemp(0, id100) == -1 ? 0 : tempX1.values[getIndexTemp(0, id100)])
        + (getIndexTemp(1, id101) == -1 ? 0 : tempX1.values[getIndexTemp(1, id101)])
        + (getIndexTemp(2, id110) == -1 ? 0 : tempX1.values[getIndexTemp(2, id110)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempX1.values[getIndexTemp(3, id111)]);
    
    float weightY0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempY0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id001) == -1 ? 0 : tempY0.values[getIndexTemp(1, id001)])
        + (getIndexTemp(2, id100) == -1 ? 0 : tempY0.values[getIndexTemp(2, id100)])
        + (getIndexTemp(3, id101) == -1 ? 0 : tempY0.values[getIndexTemp(3, id101)]);
    
    float weightY1
        = (getIndexTemp(0, id010) == -1 ? 0 : tempY1.values[getIndexTemp(0, id010)])
        + (getIndexTemp(1, id011) == -1 ? 0 : tempY1.values[getIndexTemp(1, id011)])
        + (getIndexTemp(2, id110) == -1 ? 0 : tempY1.values[getIndexTemp(2, id110)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempY1.values[getIndexTemp(3, id111)]);
    
    float weightZ0
        = (getIndexTemp(0, id000) == -1 ? 0 : tempZ0.values[getIndexTemp(0, id000)])
        + (getIndexTemp(1, id010) == -1 ? 0 : tempZ0.values[getIndexTemp(1, id010)])
        + (getIndexTemp(2, id100) == -1 ? 0 : tempZ0.values[getIndexTemp(2, id100)])
        + (getIndexTemp(3, id110) == -1 ? 0 : tempZ0.values[getIndexTemp(3, id110)]);
    
    float weightZ1
        = (getIndexTemp(0, id001) == -1 ? 0 : tempZ1.values[getIndexTemp(0, id001)])
        + (getIndexTemp(1, id011) == -1 ? 0 : tempZ1.values[getIndexTemp(1, id011)])
        + (getIndexTemp(2, id101) == -1 ? 0 : tempZ1.values[getIndexTemp(2, id101)])
        + (getIndexTemp(3, id111) == -1 ? 0 : tempZ1.values[getIndexTemp(3, id111)]);
#endif

    float sumWeights = 0;

#if USE_NORMAL_INT
    sumWeights += weight000 + weight001 + weight010 + weight011 + weight100 + weight101 + weight110 + weight111;
#endif
#if USE_ROTATED_INT
    sumWeights += weightX0 + weightX1 + weightY0 + weightY1 + weightZ0 + weightZ1;
#endif

    vec3 map = vec3(0);

#if USE_NORMAL_INT
    map += q111 * weight000
    + q110 * weight001
    + q101 * weight010
    + q100 * weight011
    + q011 * weight100
    + q010 * weight101
    + q001 * weight110
    + q000 * weight111;
#endif

#if USE_ROTATED_INT
    map += vec3(1, y, z) * weightX0
    + vec3(0, y, z) * weightX1
    + vec3(x, 1, z) * weightY0
    + vec3(x, 0, z) * weightY1
    + vec3(x, y, 1) * weightZ0
    + vec3(x, y, 0) * weightZ1;

    if(any(lessThan(ivec3(color), ivec3(maxBin))) && any(greaterThanEqual(ivec3(color), ivec3(0)))) { // only for debugging right now
        intX0.values[getIndex(ivec3(i, j, k))] = weightX0; 
        intX1.values[getIndex(ivec3(i, j, k))] = weightX1;
        intY0.values[getIndex(ivec3(i, j, k))] = weightY0;
        intY1.values[getIndex(ivec3(i, j, k))] = weightY1;
        intZ0.values[getIndex(ivec3(i, j, k))] = weightZ0;
        intZ1.values[getIndex(ivec3(i, j, k))] = weightZ1;
    }
#endif

    map *= 1 / sumWeights;
    uint trIndex = 
        uint(i + j * (maxBin+1) + k * (maxBin+1) * (maxBin+1)); 
    transformation.values[trIndex] = vec4(map, 0);

    if(any(lessThan(ivec3(color), ivec3(maxBin))))
        histogram.values[getIndex(color)] = 0;
}
